# Site Settings
title: "Forrest Williams"
subtitle: ""
description: "Data Projects and Visualizations"
url: "https://samforwill.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Logo
logo: "/assets/images/github_logo.png"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gfm
  - jekyll-feed

# Author
author:
  name: "Forrest Williams"
  avatar: "/assets/images/avatar1.jpg"
  bio: "Data analyst, election nerd, and bike-lane enthusiast"
  location: "New York, NY"
  email: "samuel.forrest.williams@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/samforwill"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/samforwill"
    - label: "Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: #resume


# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  pages:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/