title: "Forrest Williams"
subtitle: ""
description: "Data Projects and Visualizations"
url: "https://samforwill.github.io"  # or your GitHub Pages URL
baseurl: ""  # leave as "" if you're using samuelwilliams.github.io

theme: "minimal-mistakes-jekyll"

logo: "/assets/images/github_logo.png"  # Optional, replace with your logo

plugins:
  - jekyll-include-cache


author:
  name: "Forrest Williams"
  avatar: "/assets/images/avatar1.jpg"
  bio: "Data analyst, election nerd, and Jekyll tinkerer."
  location: "New York, NY"
  email: "you@example.com"       # optional
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/forrestwilliams"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/forrestwilliams"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/forrestwilliams"

include:
  - _pages

# _config.yml

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: false

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      related: true


 